# Generated by Django 2.0.9 on 2018-11-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptar',
            fields=[
                ('correo', models.EmailField(max_length=254)),
                ('run', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
    ]
