# Generated by Django 2.0.9 on 2018-11-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0002_adoptar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Rescatado', 'Rescatado'), ('Disponible', 'Disponible'), ('Adoptado', 'Adoptado')], max_length=10)),
            ],
        ),
    ]
